apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lispflow.fullname" . }}
  labels:
    {{- include "lispflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.db_password.existingSecret | default (randAlphaNum 32) | quote }}
  jwt-secret: {{ .Values.secrets.jwt_secret.existingSecret | default (randAlphaNum 64) | quote }}
  webhook-secret: {{ .Values.secrets.webhook_secret.existingSecret | default (randAlphaNum 64) | quote }}
